package net.violetunderscore.every5minutes.returns;

import java.util.Random;

public class returnRandoms {
    public static String returnMob() {
        String[] mobList = {
                "minecraft:allay",
                "minecraft:armadillo",
                "minecraft:axolotl",
                //"minecraft:bat",
                "minecraft:bee",
                "minecraft:blaze",
                "minecraft:bogged",
                "minecraft:breeze",
                "minecraft:camel",
                "minecraft:camel_husk",
                "minecraft:cat",
                "minecraft:cave_spider",
                "minecraft:chicken",
                //"minecraft:cod",
                "minecraft:copper_golem",
                "minecraft:cow",
                "minecraft:creaking",
                "minecraft:creeper",
                "minecraft:dolphin",
                //"minecraft:donkey",
                "minecraft:drowned",
                "minecraft:elder_guardian",
                "minecraft:ender_dragon",
                "minecraft:enderman",
                "minecraft:endermite",
                "minecraft:evoker",
                "minecraft:fox",
                "minecraft:frog",
                "minecraft:ghast",
                "minecraft:giant",
                //"minecraft:glow_squid",
                "minecraft:goat",
                "minecraft:guardian",
                "minecraft:happy_ghast",
                "minecraft:hoglin",
                "minecraft:horse",
                "minecraft:husk",
                "minecraft:illusioner",
                "minecraft:iron_golem",
                "minecraft:llama",
                "minecraft:magma_cube",
                "minecraft:mooshroom",
                //"minecraft:mule",
                "minecraft:nautilus",
                //"minecraft:ocelot",
                "minecraft:panda",
                "minecraft:parched",
                "minecraft:parrot",
                "minecraft:phantom",
                "minecraft:pig",
                "minecraft:piglin",
                "minecraft:piglin_brute",
                "minecraft:pillager",
                "minecraft:polar_bear",
                "minecraft:pufferfish",
                "minecraft:rabbit",
                "minecraft:ravanger",
                "minecraft:salmon",
                "minecraft:sheep",
                "minecraft:shulker",
                "minecraft:silverfish",
                "minecraft:skeleton",
                "minecraft:skeleton_horse",
                "minecraft:slime",
                "minecraft:sniffer",
                "minecraft:snow_golem",
                "minecraft:spider",
                "minecraft:squid",
                "minecraft:stray",
                "minecraft:strider",
                "minecraft:tadpole",
                //"minecraft:trader_llama",
                //"minecraft:tropical_fish",
                "minecraft:turtle",
                "minecraft:vex",
                "minecraft:villager",
                "minecraft:vindicator",
                "minecraft:warden",
                "minecraft:witch",
                "minecraft:wither",
                "minecraft:wither_skeleton",
                "minecraft:wolf",
                "minecraft:zoglin",
                "minecraft:zombie",
                "minecraft:zombie_horse",
                "minecraft:zombie_nautilus",
                "minecraft:zombie_villager",
                "minecraft:zombified_piglin",
        };
        Random random = new Random();
        return mobList[random.nextInt(0, mobList.length - 1)];
    }

    public static String returnColor() {
        String[] colorList = {
                "Red",
                "Orange",
                "Yellow",
                "Green",
                "Blue",
                "Purple",
                "White",
                "Gray",
                "Black",
                "Brown"
        };
        Random random = new Random();
        return colorList[random.nextInt(0, colorList.length - 1)];
    }

    public static String returnPotionEffect() {
        String[] effectList = {
                "minecraft:speed",
                "minecraft:slowness",
                "minecraft:haste",
                "minecraft:mining_fatigue",
                "minecraft:strength",
                "minecraft:instant_health",
                "minecraft:instant_damage",
                "minecraft:jump_boost",
                "minecraft:nausea",
                "minecraft:regeneration",
                "minecraft:resistance",
                "minecraft:fire_resistance",
                "minecraft:water_breathing",
                "minecraft:invisibility",
                "minecraft:blindness",
                "minecraft:night_vision",
                "minecraft:hunger",
                "minecraft:weakness",
                "minecraft:poison",
                "minecraft:wither",
                "minecraft:health_boost",
                "minecraft:absorption",
                "minecraft:saturation",
                "minecraft:glowing",
                "minecraft:levitation",
                "minecraft:luck",
                "minecraft:unluck",
                "minecraft:slow_falling",
                "minecraft:conduit_power",
                "minecraft:dolphins_grace",
                "minecraft:bad_omen",
                "minecraft:hero_of_the_village",
                "minecraft:darkness",
                "minecraft:wind_charged"
        };
        Random random = new Random();
        return effectList[random.nextInt(effectList.length)];
    }
}
